In [4]:
import os
os.getcwd()

'/home/danielrezende/projects/pibic/checking-the-algorithms/notebooks'

In [7]:
import pandas as pd

# Load the uploaded CSV to inspect its structure
file_path = "../results/results.csv"
data = pd.read_csv(file_path)

# Display the first few rows of the dataset to understand its structure
data.head()

  submissionName1          submissionName2  averageSimilarity  maxSimilarity
0  problem_064.py  problem_064_minified.py                1.0            1.0
1  problem_076.py  problem_076_minified.py                1.0            1.0
2  problem_036.py  problem_036_minified.py                1.0            1.0
3  problem_015.py  problem_015_minified.py                1.0            1.0
4  problem_686.py  problem_686_minified.py                1.0            1.0

In [8]:
data['problem1'] = data['submissionName1'].str.extract(r'problem_(\d+)', expand=False)
data.head()

,submissionName1,submissionName2,averageSimilarity,maxSimilarity,problem1
0,problem_064.py,problem_064_minified.py,1.0,1.0,064
1,problem_076.py,problem_076_minified.py,1.0,1.0,076
2,problem_036.py,problem_036_minified.py,1.0,1.0,036
3,problem_015.py,problem_015_minified.py,1.0,1.0,015
4,problem_686.py,problem_686_minified.py,1.0,1.0,686

In [9]:
data['problem2'] = data['submissionName2'].str.extract(r'problem_(\d+)', expand=False)
data.head()

,submissionName1,submissionName2,averageSimilarity,maxSimilarity,problem1,problem2
0,problem_064.py,problem_064_minified.py,1.0,1.0,064,064
1,problem_076.py,problem_076_minified.py,1.0,1.0,076,076
2,problem_036.py,problem_036_minified.py,1.0,1.0,036,036
3,problem_015.py,problem_015_minified.py,1.0,1.0,015,015
4,problem_686.py,problem_686_minified.py,1.0,1.0,686,686

In [11]:
data['ground_truth'] = data['problem1'] == data['problem2']
data.head()

,submissionName1,submissionName2,averageSimilarity,maxSimilarity,problem1,problem2,ground_truth
0,problem_064.py,problem_064_minified.py,1.0,1.0,064,064,True
1,problem_076.py,problem_076_minified.py,1.0,1.0,076,076,True
2,problem_036.py,problem_036_minified.py,1.0,1.0,036,036,True
3,problem_015.py,problem_015_minified.py,1.0,1.0,015,015,True
4,problem_686.py,problem_686_minified.py,1.0,1.0,686,686,True

In [12]:
threshold = 0.8
data['prediction'] = data['averageSimilarity'] > threshold
data.head()

,submissionName1,submissionName2,averageSimilarity,maxSimilarity,problem1,problem2,ground_truth,prediction
0,problem_064.py,problem_064_minified.py,1.0,1.0,064,064,True,True
1,problem_076.py,problem_076_minified.py,1.0,1.0,076,076,True,True
2,problem_036.py,problem_036_minified.py,1.0,1.0,036,036,True,True
3,problem_015.py,problem_015_minified.py,1.0,1.0,015,015,True,True
4,problem_686.py,problem_686_minified.py,1.0,1.0,686,686,True,True

In [18]:
type(data)

pandas.core.frame.DataFrame

In [17]:
from sklearn.metrics import precision_score, recall_score, f1_score


precision = precision_score(data["ground_truth"], data["prediction"])
recall = recall_score(data["ground_truth"], data["prediction"])
f1 = f1_score(data["ground_truth"], data["prediction"])

print(f"Precision: {precision:.2f}")
print(f"Recall: {recall:.2f}")
print(f"f1-score: {f1:.2f}")
print(f"({precision:.2f}, {recall:.2f}, {f1:.2f})")

Precision: 1.00
Recall: 0.82
f1-score: 0.90
(1.00, 0.82, 0.90)